
import Head from "next/head";

import Nav from "~/components/Navbar/navbar";
import { api } from "~/utils/api";



import { type NextPage } from "next";
import { LoadingMessage,ErrorMessage } from "~/components/ErrorMessage";
import { MuliColumnVideo } from "~/components/VideoComponent"
import HeroSection from "~/components/Herosection";

const Home: NextPage = () => {

  const { data, isLoading, error} = api.video.getRandomVideos.useQuery(20);

  const Error = () => {
    if (isLoading) {
      return <LoadingMessage />;
    } else if (error ?? !data) {
      return (
        <ErrorMessage
          icon="GreenPlay"
          message="No Videos"
          description="Sorry there is no videos at this time."
        />
      );
    } else {
      return <></>;
    }
  };

  return (
    <>
      <Head>
        <title>Gimbals.io</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
     
      <section className="flex flex-col items-center justify-center gap-4 py-8 md:py-10">
      <HeroSection/>
       
        <div>
        {!data ? (
          <Error />
        ) : (
          <>
               <MuliColumnVideo
              videos={data.videos.map((video) => ({
                id: video?.id ?? "",
                title: video?.title ?? "",
                thumbnailUrl: video?.thumbnailUrl ?? "",
                createdAt: video?.createdAt ?? new Date(),
                views: video?.views ?? 0,
              }))}
              users={data.users.map((user) => ({
                name: user?.name ?? "",
                image: user?.image ?? "",
              }))}
            />
            </>
            )}
        </div>
        
      </section>
      
    </>
  );
}


export default Home;