import Head from "next/head";
import Wordchanger from "~/components/Wordchanger/wordchanger";
import CatNavbar from "~/components/Catnavbar/catnavbar";
import Layout from "~/components/layout";
import { Input } from "@nextui-org/react";
import { Search } from "lucide-react";


export default function Home() {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Layout>
    <div>
    <section className="flex flex-col items-center justify-center gap-4 py-8 md:py-10">
      <div className="inline-block max-w-lg text-center justify-center">
        <span className="text-6xl font-bold">
          Find&nbsp;
        </span>
        <Wordchanger />
        <span className="text-6xl font-bold">creators for your next shoot.</span>
       
      </div>

      <div className="w-full max-w-md px-4">
      <Input
        isClearable
        radius="lg"
        size="lg"
        classNames={{
          label: "text-black/50 dark:text-white/90",
          input: [
            "bg-transparent",
            "text-black/90 dark:text-white/90",
            "placeholder:text-default-700/50 dark:placeholder:text-white/60",
          ],
          innerWrapper: "bg-transparent",
          inputWrapper: [
            "shadow-xl",
            "bg-default-200/50",
            "dark:bg-default/60",
            "backdrop-blur-xl",
            "backdrop-saturate-200",
            "hover:bg-default-200/70",
            "dark:hover:bg-default/70",
            "group-data-[focused=true]:bg-default-200/50",
            "dark:group-data-[focused=true]:bg-default/60",
            "!cursor-text",
          ],
        }}
        placeholder="Type to search..."
        startContent={
          <Search />} />
    
      
      </div>
      </section>
      <div>
        <CatNavbar />
        </div>
    </div>
     
      
        </Layout>
       
      
    </>
  );
}